################################################################################
# Quant Agent Platform – Development stack
#   • app      – Python container with DuckDB embedded
#   • qdrant   – vector DB for news embeddings
#
# One-command startup:
#   docker compose -f docker/docker-compose.dev.yml up --build
################################################################################

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: qap-app
    command: ["python", "-q"]
    env_file:
      - ../.env
    volumes:
      - ../app:/app
      - ../configs:/configs:ro
      - data-volume:/data
    working_dir: /app
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - qdrant-data:/qdrant/storage

configs:
  qdrant_config:
    content: |
      log_level: INFO


volumes:
  qdrant-data:
  data-volume:
